---

sample: ''
reads: [1,2,3]
barcodes: {'tn5':['CGTACTAG','TCCTGAGC','TCATGAGC','CCTGAGAT'],'tnh':['TAAGGCGA','GCTACGCT','AGGCTCCG','CTGCGCAT']}
genome: /home/morelli/scGET_files/genome/hg38.fa
threads: 8
cell_number: 5000
scatacc_path: '/home/morelli/scatACC'
input_path: ''
input_list: ''
output_path: ''
...