---

sample: ''
reads: [1,2,3]
barcodes: {'tn5':['CGTACTAG','TCCTGAGC','TCATGAGC','CCTGAGAT'],'tnh':['TAAGGCGA','GCTACGCT','AGGCTCCG','CTGCGCAT']}
genome: /beegfs/scratch/ric.cosr/ric.cosr/CRUK_AIRC_Accelerator/Test_MD/genome/bwa/GRCm38
bed_file: /beegfs/scratch/ric.cosr/ric.cosr/CRUK_AIRC_Accelerator/Test_MD/genome/GRCm38.5kb.bed
threads: 8
cell_number: 5000
scatacc_path: '../repo/scatACC'
input_path: ''
input_list: ''
output_path: ''
binary: False
tnh: True
tn5: True
atac: False
...
