---

sample: ''
reads: [1,2,3]
barcodes: {'tn5':['CGTACTAG','TCCTGAGC','TCATGAGC','CCTGAGAT'],'tnh':['TAAGGCGA','GCTACGCT','AGGCTCCG','CTGCGCAT']}
read_length: 50
genome_index: ''
genome_fasta: '' 
genome: ''
bed_file: ''
threads: 8
cell_number: 5000
scatacc_path: '../repo/scatACC'
input_path: ''
input_list: ''
output_path: ''
binary: False
tnh: True
tn5: True
atac: False
...
