---

sample: 8_7w_scGETseq
reads: [1,2,3]
barcodes: {'tn5':['CGTACTAG','TCCTGAGC','TCATGAGC','CCTGAGAT'],'tnh':['TAAGGCGA','GCTACGCT','AGGCTCCG','CTGCGCAT']}
genome: ../genome/hg38.fa
threads: 8
cell_number: 5000
path: ''
...
