---

sample: ''
reads: [1,2,3]
barcodes: {'tn5':['CGTACTAG','TCCTGAGC','TCATGAGC','CCTGAGAT'],'tnh':['TAAGGCGA','GCTACGCT','AGGCTCCG','CTGCGCAT']}
genome: ## PATH TO BWA GENOME 
bc_pattern: CCCCCCCCCCCCCCCC
bed_file: ##PATH TO PEAKS/INTERVALS BED FILE
read_length: 50
genome_index: ## PATH TO CHROMAP GENOME INDEX
genome_fasta: ## PATH TO GENOME FASTA
genome: ''
bed_file: ''
threads: 8
cell_number: 5000
scatacc_path: ## PATH TO scatACC sources
input_path: ## PATH TO BASEDIR FOR ALL THE ANALYSIS
input_list: input_files.txt
output_path: ## PATH TO OUTPUT DIR
binary: False
tnh: True
tn5: True
atac: False
...
